CREATE DATABASE TRENINGSDAGBOK;

/* TRENING */

CREATE TABLE TRENING (
	trening_id		INT NOT NULL,
	form			INT NOT NULL CHECK (form >= 1 AND form <= 10),
	prestasjon		INT NOT NULL CHECK (prestasjon >= 1 AND prestasjon <= 10),
	dato			DATE NOT NULL,
	tid 			TIME NOT NULL,
	varighet		FLOAT NOT NULL,
	CONSTRAINT TRENING_PK PRIMARY KEY (trening_id)
);

CREATE TABLE NOTAT (
	trening_id		INT NOT NULL,
	mal				VARCHAR(200),
	tips			VARCHAR(200),
	CONSTRAINT PRIMARY KEY (trening_id),
	CONSTRAINT TRENING_FK FOREIGN KEY (trening_id) REFERENCES TRENING(trening_id)
					ON UPDATE CASCADE
					ON DELETE CASCADE
);

/* ØVELSER */

CREATE TABLE OVELSE (
	ovelse_id		INT NOT NULL,
	navn			VARCHAR(30) NOT NULL,
	beskrivelse		VARCHAR(200) NOT NULL,
	CONSTRAINT OVELSEID_PK PRIMARY KEY (ovelse_id)
);

CREATE TABLE OVELSEERSTATTER (
	ovelse_id		INT NOT NULL,
	erstatter_id	INT NOT NULL,
	CONSTRAINT OVELSEERSTATTER_PK PRIMARY KEY (ovelse_id, erstatter_id),
	CONSTRAINT OVELSEERSTATTER_OVELSE_FK FOREIGN KEY (ovelse_id) REFERENCES OVELSE(ovelse_id)
					ON UPDATE CASCADE
					ON DELETE CASCADE,
	CONSTRAINT OVELSEERSTATTER_ERSTATTER_FK FOREIGN KEY (erstatter_id) REFERENCES OVELSE(ovelse_id)
					ON UPDATE CASCADE
					ON DELETE CASCADE
);

/* ØVELSETYPER */

CREATE TABLE STYRKE (
	ovelse_id		INT NOT NULL,
	sett			INT NOT NULL,
	repetisjon		INT NOT NULL,
	belastning		INT NOT NULL,
	CONSTRAINT STYRKE_PK PRIMARY KEY (ovelse_id),
	CONSTRAINT STYRKE_FK FOREIGN KEY (ovelse_id) REFERENCES OVELSE(ovelse_id)
					ON UPDATE CASCADE
					ON DELETE CASCADE
);


CREATE TABLE KONDISJON (
	ovelse_id		INT NOT NULL,
	sett			INT NOT NULL,
	repetisjon		INT NOT NULL,
	belastning		INT NOT NULL,
	CONSTRAINT KONDISJON_PK PRIMARY KEY (ovelse_id),
	CONSTRAINT KONDISJON_FK FOREIGN KEY (ovelse_id) REFERENCES OVELSE(ovelse_id)
					ON UPDATE CASCADE
					ON DELETE CASCADE
);

CREATE TABLE UTHOLDENHET (
	ovelse_id 		INT NOT NULL,
	lengde 			FLOAT NOT NULL,
	CONSTRAINT UTHOLDENHET_PK PRIMARY KEY (ovelse_id),
	CONSTRAINT UTHOLDENHET_FK FOREIGN KEY (ovelse_id) REFERENCES OVELSE(ovelse_id)
					ON UPDATE CASCADE
					ON DELETE CASCADE
);


CREATE TABLE PUNKT (
	ovelse_id		INT NOT NULL,
	tid				TIME NOT NULL,
	puls			INT NOT NULL,
	lengdegrad		FLOAT NOT NULL,
	breddegrad		FLOAT NOT NULL,
	moh				FLOAT NOT NULL,
	CONSTRAINT PUNKT_PK PRIMARY KEY(ovelse_id, tid),
	CONSTRAINT PUNKT_FK FOREIGN KEY (ovelse_id) REFERENCES UTHOLDENHET(ovelse_id)
					ON UPDATE CASCADE
					ON DELETE CASCADE
);

/* LOGGFØRING */

CREATE TABLE LOGG (
	logg_id		 	INT NOT NULL,
    sett 			INT,
	belastning	 	INT,
    repetisjon 		INT,
    lengde 			FLOAT,
	CONSTRAINT LOGG_PK PRIMARY KEY (logg_id)
);

/* RELASJONER */

CREATE TABLE TRENINGSPLAN (
	ovelse_id		INT NOT NULL,
	trening_id		INT NOT NULL,
	CONSTRAINT TRENINGSPLAN_PK PRIMARY KEY (ovelse_id, trening_id),
	CONSTRAINT TRENINGSPLAN_OVELSE_FK FOREIGN KEY (ovelse_id) REFERENCES OVELSE(ovelse_id)
					ON UPDATE CASCADE
					ON DELETE CASCADE,
	CONSTRAINT TRENINGSPLAN_TRENING_FK FOREIGN KEY (trening_id) REFERENCES TRENING(trening_id)
					ON UPDATE CASCADE
					ON DELETE CASCADE
);

CREATE TABLE LOGGOVELSER (
    trening_id 		INT NOT NULL,
	logg_id 		INT NOT NULL,
	ovelse_id		INT NOT NULL,
    CONSTRAINT PRIMARY KEY (logg_id, trening_id, ovelse_id),
    CONSTRAINT LOGGOVELSER_LOGG_FK FOREIGN KEY (logg_id) REFERENCES LOGG(logg_id)
					ON UPDATE CASCADE
					ON DELETE CASCADE,
	CONSTRAINT LOGGOVELSER_OVELSE_FK FOREIGN KEY (ovelse_id) REFERENCES OVELSE(ovelse_id)
					ON UPDATE CASCADE
					ON DELETE CASCADE,
    CONSTRAINT LOGGOVELSER_TRENING_FK FOREIGN KEY (trening_id) REFERENCES TRENING(trening_id)
					ON UPDATE CASCADE
					ON DELETE CASCADE
);

/* SCHEMA 

TRENING (		trening_id INT	form INT		prestasjon INT		dato DATE			tid TIME		varighet FLOAT);
NOTAT (			trening_id INT	mal VARCHAR		tips varchar)
TRENINGSPLAN(	trening_id INT	ovelse_id INT)
OVELSE(			ovelse_id INT	navn VARCHAR	beskrivelse VARCHAR)
STYRKE(			ovelse_id INT	sett INT		repetisjon INT		belastning INT)
KONDISJON(		ovelse_id INT	sett INT		repetisjon INT		belastning INT)
UTHOLDENHET(	ovelse_id INT	lengde)
PUNKT(			ovelse_id INT	tid TIME		puls INT			lengdegrad FLOAT	bredderad FLOAT	moh INT)
LOGGOVELSER(	trening_id INT	logg_id INT		ovelse_id INT	)
LOGG (			logg_id INT		sett INT		repetisjon INT		belastning INT			lengde INT)

*/
/* TESTDATA */

INSERT INTO TRENING VALUES(1,9,6, '2017-04-16', '15:15', 1.5);
INSERT INTO TRENING VALUES(2,9,6, '2017-04-16', '15:15', 1.5);

INSERT INTO NOTAT VALUES(1, 'Fullfør alt', 'Drikk mye vann');
INSERT INTO OVELSE VALUES(1, "benkpress", "DO YOU EVEN LIFT BRO?");
INSERT INTO STYRKE VALUES(1, 3, 5, 100);
INSERT INTO TRENINGSPLAN VALUES(1,1);
INSERT INTO LOGG VALUES(1, 3, 5, 100, NULL);
INSERT INTO LOGGOVELSER VALUES(1, 1, 1);

INSERT INTO OVELSE VALUES(2, "deadlift", "DO YOU EVEN LIFT BRO?");
INSERT INTO STYRKE VALUES(2, 2, 7, 200);
INSERT INTO TRENINGSPLAN VALUES(1,2);
INSERT INTO LOGG VALUES(2, 2, 7, 200, NULL);
INSERT INTO LOGGOVELSER VALUES(2, 2, 1);


/* QUERIES 
*
*
*
*
*/


/* TRENINGSPLAN */

SELECT *
FROM TRENINGSPLAN JOIN TRENING ON TRENING.trening_id = TRENINGSPLAN.trening_id
			JOIN OVELSE ON OVELSE.ovelse_id = TRENINGSPLAN.ovelse_id;
            
/*  */
SELECT *
FROM LOGGOVELSER JOIN TRENING ON TRENING.trening_id = LOGGOVELSER.trening_id
			JOIN OVELSE ON OVELSE.ovelse_id = LOGGOVELSER.ovelse_id
            JOIN LOGG ON LOGG.logg_id = LOGGOVELSER.logg_id